<a href="https://colab.research.google.com/github/poonamkhot123/Numpy-Pandas-Library/blob/main/Numpy_with_CampusX_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# we can say 1D aaray as vector
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# we can say 2D array as matrix
b = np.array([[1,2,3,5],[3,4,5,6]])
print(b)

[[1 2 3 5]
 [3 4 5 6]]


In [ ]:
# 3D = tensor
c = np.array([[[1,2,3],[3,4,5],[3,5,6]]])
print(c)

[[[1 2 3]
  [3 4 5]
  [3 5 6]]]


In [ ]:
#dtype
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [ ]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [ ]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# np.arange ( to create a array)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# with reshape = convert array to other shape.
np.arange(1,11).reshape(5,2)  # 5 rows, 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.zeros
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))  # 1st random class,2nd random method

array([[0.4144827 , 0.02120808, 0.80236068, 0.51123018],
       [0.89768572, 0.48946876, 0.67890802, 0.09442322],
       [0.17344094, 0.36324845, 0.43618111, 0.77094065]])

In [ ]:
# np.linspace(linearly space = distance between two points are same)
np.linspace(-10,10,10) # -10 lower range,10 upper range,10 no.of items.

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Atrributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#ndim
a2.ndim

2

In [ ]:
a3.ndim

3

In [ ]:
# shape
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
# size = gives no. of items
a3.size

8

In [ ]:
a2.size

12

In [ ]:
# itemsize
a2.itemsize

8

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatypes

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operatinos

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 > 15


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations = between two arrays
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array functions


In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[78., 30., 68.],
       [30., 84., 60.],
       [26., 67., 49.]])

In [ ]:
# max/min/sum/prod
np.max(a1)

np.float64(84.0)

In [ ]:
np.min(a1)

np.float64(4.0)

In [ ]:
np.sum(a1)

np.float64(543.0)

In [ ]:
np.prod(a1)

np.float64(1255434409958400.0)

In [ ]:
# max in each row
# 0 means column , 1 means row
np.max(a1,axis=1)

array([90., 86., 80.])

In [ ]:
# min in each row
np.min(a1,axis=1)

array([ 4., 46., 41.])

In [ ]:
# max in each column
np.max(a1,axis=0)

array([86., 90., 80.])

In [ ]:
# min in each column
np.min(a1,axis=0)

array([ 4., 46., 63.])

In [ ]:
# mean/median/std/var
np.mean(a1)

np.float64(60.333333333333336)

In [ ]:
# find mean column wise and row wise
np.mean(a1,axis=0)

array([43.66666667, 63.33333333, 74.        ])

In [ ]:
np.median(a2)

np.float64(17.5)

In [ ]:
np.median(a3)

np.float64(3.5)

In [ ]:
np.std(a1)

np.float64(25.978623691198287)

In [ ]:
np.var(a1)

np.float64(674.8888888888889)

In [ ]:
# trigonometric functions
np.sin(a1)

array([[-0.7568025 ,  0.89399666,  0.1673557 ],
       [-0.92345845,  0.90178835, -0.44411267],
       [-0.15862267, -0.55878905, -0.99388865]])

In [ ]:
np.cos(a1)

array([[-0.65364362, -0.44807362,  0.98589658],
       [-0.38369844, -0.43217794, -0.89597095],
       [-0.98733928, -0.82930983, -0.11038724]])

In [ ]:
np.tan(a1)

array([[ 1.15782128, -1.99520041,  0.16974975],
       [ 2.40672971, -2.08661353,  0.49567753],
       [ 0.1606567 ,  0.6738001 ,  9.00365495]])

# Dot Product

In [ ]:
# Dot Product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log / exponent
np.log(a1)

array([[4.35670883, 3.40119738, 4.21950771],
       [3.40119738, 4.4308168 , 4.09434456],
       [3.25809654, 4.20469262, 3.8918203 ]])

In [ ]:
np.exp(a1)

array([[7.49841700e+33, 1.06864746e+13, 3.40427605e+29],
       [1.06864746e+13, 3.02507732e+36, 1.14200739e+26],
       [1.95729609e+11, 1.25236317e+29, 1.90734657e+21]])

In [ ]:
# round/floor/cell
np.round(np.random.random((2,3))* 100)

array([[94., 71., 70.],
       [21., 67., 77.]])

In [ ]:
np.floor(np.random.random((2,3))* 100)

array([[46.,  9., 29.],
       [34.,  9., 80.]])

In [ ]:
np.ceil(np.random.random((2,3))* 100)

array([[83., 43., 28.],
       [95., 18., 41.]])

# Indexing and Slicing


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
# get last item = negative indexing
a1[-1]

np.int64(9)

In [ ]:
# get first item = starts from from
a1[0]

np.int64(0)

In [ ]:
# to get a particular element,

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# getting element from the 3D array.( Suppose want 5)
a3[1,0,1]

np.int64(5)

In [ ]:
# suppose we want 2
a3[0,1,0]

np.int64(2)

In [ ]:
# suppose we want 6
a3[1,1,0]

np.int64(6)

# Slicing
* if we want multiple elements from an array


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# if we want first row.(means entire column thats why : used)
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
# we want 3rd column.(means entire row thats why : used)
a2[:,2]

array([ 2,  6, 10])

In [ ]:
# if we want 5 6 9 and 10 then
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# if we want 0 3 8 and 11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
# if we want 1,3,9 and 11
a2[::2,1::2]

In [ ]:
a2[1,::3]

array([4, 7])

# 3D Array

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# if we want print all iterms in 3D array.
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshape

In [ ]:
# transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# another method for transpose
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel = covert ndim array into 1D.
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
a1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Stacking
joining of two numpy array.

In [ ]:
# Horizontal Stacking.
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
display(np.vstack((a4,a5)))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
* Horizontal splitting = vertical split
* Vertical splitting = Horizontal split

In [ ]:
# Horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2) # 2 = two equal halves

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.hsplit(a4,4) # four equal parts

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]