<a href="https://colab.research.google.com/github/poonamkhot123/Numpy-practice/blob/main/Session_15_Numpy_trick_with_CampusX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [ ]:
a = np.random.randint(1,100,15)
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[49, 29, 57, 51],
       [28, 49, 75, 62],
       [68, 91, 28, 86],
       [64, 93, 72, 41],
       [18, 96, 44, 73],
       [15, 92, 94, 48]])

In [ ]:
np.sort(b)

array([[29, 49, 51, 57],
       [28, 49, 62, 75],
       [28, 68, 86, 91],
       [41, 64, 72, 93],
       [18, 44, 73, 96],
       [15, 48, 92, 94]])

In [ ]:
np.sort(a)

array([ 4, 11, 37, 46, 47, 55, 57, 58, 63, 69, 77, 89, 90, 92, 95])

In [ ]:
# decending order of sorting
np.sort(a)[::-1]

array([95, 92, 90, 89, 77, 69, 63, 58, 57, 55, 47, 46, 37, 11,  4])

# np.append
* the numpy.append() values along the mentioned axis at the end of the array.

In [ ]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [ ]:
np.append(a,200)

array([ 47,  90,  63,  37,  58,  95,  11,  92,  69,  57,  77,   4,  55,
        46,  89, 200])

In [ ]:
b

array([[49, 29, 57, 51],
       [28, 49, 75, 62],
       [68, 91, 28, 86],
       [64, 93, 72, 41],
       [18, 96, 44, 73],
       [15, 92, 94, 48]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[49., 29., 57., 51.,  1.],
       [28., 49., 75., 62.,  1.],
       [68., 91., 28., 86.,  1.],
       [64., 93., 72., 41.,  1.],
       [18., 96., 44., 73.,  1.],
       [15., 92., 94., 48.,  1.]])

# np.concatenate
* numpy.concatenate() function concatenate a sequence of arrays algong as existing axis.

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
* with the help of np.unique method,we can get unique values from an array.

In [ ]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])

print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [20]:
np.unique(f)

array([1, 2, 3])

# np.expand_dims
* with the help of Numpy.expand_dims() method,we can get the expanded dimensions of an array.

In [21]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [22]:
np.expand_dims(a,axis=0)

array([[47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89]])

In [23]:
np.expand_dims(a,axis=1)

array([[47],
       [90],
       [63],
       [37],
       [58],
       [95],
       [11],
       [92],
       [69],
       [57],
       [77],
       [ 4],
       [55],
       [46],
       [89]])

# np.where
* the numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [24]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [25]:
# find all indices with value greater than 50.
np.where(a>50)

(array([ 1,  2,  4,  5,  7,  8,  9, 10, 12, 14]),)

In [28]:
# replace all values > 50 with 0.
np.where(a>50,0,a)

array([47,  0,  0, 37,  0,  0, 11,  0,  0,  0,  0,  4,  0, 46,  0])

In [29]:
np.where(a%2 == 0,0,a)

array([47,  0, 63, 37,  0, 95, 11,  0, 69, 57, 77,  0, 55,  0, 89])

# np.argmax
* The numpy.argmax() returns indices of the max element of the array in a particular axis.

In [30]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [31]:
np.argmax(a)

np.int64(5)

In [32]:
b

array([[49, 29, 57, 51],
       [28, 49, 75, 62],
       [68, 91, 28, 86],
       [64, 93, 72, 41],
       [18, 96, 44, 73],
       [15, 92, 94, 48]])

In [33]:
np.argmax(b,axis=0)

array([2, 4, 5, 2])

In [34]:
# np.argmin
np.argmin(a)

np.int64(11)

# np.cumsum
* numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [35]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [36]:
np.cumsum(a)

array([ 47, 137, 200, 237, 295, 390, 401, 493, 562, 619, 696, 700, 755,
       801, 890])

In [37]:
b

array([[49, 29, 57, 51],
       [28, 49, 75, 62],
       [68, 91, 28, 86],
       [64, 93, 72, 41],
       [18, 96, 44, 73],
       [15, 92, 94, 48]])

In [39]:
np.cumsum(b,axis=0)

array([[ 49,  29,  57,  51],
       [ 77,  78, 132, 113],
       [145, 169, 160, 199],
       [209, 262, 232, 240],
       [227, 358, 276, 313],
       [242, 450, 370, 361]])

In [40]:
np.cumsum(b,axis=1)

array([[ 49,  78, 135, 186],
       [ 28,  77, 152, 214],
       [ 68, 159, 187, 273],
       [ 64, 157, 229, 270],
       [ 18, 114, 158, 231],
       [ 15, 107, 201, 249]])

In [41]:
# np.comprod
np.cumprod(a)

array([                  47,                 4230,               266490,
                    9860130,            571887540,          54329316300,
               597622479300,       54981268095600,     3793707498596400,
         216241327419994800, -1796161862369952016, -7184647449479808064,
       -7773984173488859584, -7115134580006060160, -6057679114414599296])

# np.percentile
* numpy.percentile() function used to compute the nth percentile of the given data( array elements) along the specified axis.

In [42]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [44]:
np.percentile(a,100)

np.float64(21.400000000000006)

In [45]:
np.percentile(a,0)

np.float64(4.0)

In [46]:
np.percentile(a,50)

np.float64(58.0)

# np.histogram
* Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [47]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [48]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 0, 1, 2, 3, 2, 1, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef
* return perason product moment correlation coefficient.

In [49]:
salary = np.array([20000,40000,25000,35000,60000])
experience= np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin
* with the help.isin() method,we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [50]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [51]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([90])

# np.flip
* the numpy.flip() function reverses the order of array elements along the specified axis,preserving the shape of the array.


In [52]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [53]:
np.flip(a)

array([89, 46, 55,  4, 77, 57, 69, 92, 11, 95, 58, 37, 63, 90, 47])

In [54]:
b

array([[49, 29, 57, 51],
       [28, 49, 75, 62],
       [68, 91, 28, 86],
       [64, 93, 72, 41],
       [18, 96, 44, 73],
       [15, 92, 94, 48]])

In [55]:
np.flip(b)

array([[48, 94, 92, 15],
       [73, 44, 96, 18],
       [41, 72, 93, 64],
       [86, 28, 91, 68],
       [62, 75, 49, 28],
       [51, 57, 29, 49]])

In [56]:
np.flip(b,axis=0)

array([[15, 92, 94, 48],
       [18, 96, 44, 73],
       [64, 93, 72, 41],
       [68, 91, 28, 86],
       [28, 49, 75, 62],
       [49, 29, 57, 51]])

In [57]:
np.flip(b,axis=1)

array([[51, 57, 29, 49],
       [62, 75, 49, 28],
       [86, 28, 91, 68],
       [41, 72, 93, 64],
       [73, 44, 96, 18],
       [48, 94, 92, 15]])

# np.put
* the numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [58]:
a

array([47, 90, 63, 37, 58, 95, 11, 92, 69, 57, 77,  4, 55, 46, 89])

In [59]:
np.put(a,[0,1],[110,530])

In [60]:
a

array([110, 530,  63,  37,  58,  95,  11,  92,  69,  57,  77,   4,  55,
        46,  89])

# np.delete
* the numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [61]:
a

array([110, 530,  63,  37,  58,  95,  11,  92,  69,  57,  77,   4,  55,
        46,  89])

In [62]:
np.delete(a,0)

array([530,  63,  37,  58,  95,  11,  92,  69,  57,  77,   4,  55,  46,
        89])

In [63]:
a

array([110, 530,  63,  37,  58,  95,  11,  92,  69,  57,  77,   4,  55,
        46,  89])

In [64]:
np.delete(a,[0,2,4])

array([530,  37,  95,  11,  92,  69,  57,  77,   4,  55,  46,  89])

# Set Functions
* np.union1d
* np.intersect1d
* np.setdiff1d
* np.setxor1d
* np.in1d

In [65]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
np.intersect1d(m,n)

array([3, 4, 5])

In [67]:
np.setdiff1d(m,n)

array([1, 2])

In [68]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [69]:
np.in1d(m,1)

/tmp/ipython-input-3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

# np.clip
* numpy.clip() function is used to clip (limit) the values in an array.

In [70]:
a

array([110, 530,  63,  37,  58,  95,  11,  92,  69,  57,  77,   4,  55,
        46,  89])

In [71]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 63, 37, 58, 75, 25, 75, 69, 57, 75, 25, 55, 46, 75])